### ISSUE TITLE
module 'Crypto.Cipher.AES' has no attribute 'AESCipher'

### ISSUE THREAD

**Issue by 1luvc0d3** [bschoening/fpe#1]
Hi  There,

I'm running this on Python  3.9.2 and I'm getting the package ff-3.py 

\lib\site-packages\ff3\ff3.py", line 90, in __init__  self.aesBlock = AES.AESCipher(reverse_string(self.key))

Code from ff-3.py line 90 
 # aes.NewCipher automatically returns the correct block based on the length of the key
        # Always use the reversed key since Encrypt and Decrypt call ciph expecting that

        self.aesBlock = AES.AESCipher(reverse_string(self.key))

I've imported the package crypto. cipher but I couldn't find the AESCipher but it seems to be under crypto, let me know what do you think?

**Comment by bschoening** [comment]
I have updated ff3.py to use pycryptodome instead of pycrypto.  Check that you have the latest version of the file ff3.py and that you have pycryptodome installed.

Pycrypto is no longer maintained and should be uninstalled prior to installing pycryptodome.
